import { Client, Payment, PaymentItem, WorkEntry } from '../types';

export const INITIAL_CLIENTS: Client[] = [
    {
        id: 'cli_carlos',
        name: 'Carlos Ruiz',
        company: 'CR Consultores',
        email: 'carlos@crconsultores.com',
        phone: '+34 612 345 678',
        hourlyRate: 20,
        currency: 'EUR',
        billingFrequency: 'daily',
        billingStartDate: '2026-08-01',
        notes: 'Cliente con facturación diaria al finalizar jornada.',
        active: true,
        createdAt: '2026-08-01',
    },
    {
        id: 'cli_marta',
        name: 'Marta Gómez',
        company: 'Marta Tech Solutions',
        email: 'marta@martatech.io',
        phone: '+34 699 887 766',
        hourlyRate: 25,
        currency: 'EUR',
        billingFrequency: 'weekly',
        billingStartDate: '2026-08-01',
        notes: 'Cobro semanal los viernes.',
        active: true,
        createdAt: '2026-08-01',
    },
    {
        id: 'cli_nova',
        name: 'Agencia Nova Digital',
        company: 'Nova Digital S.L.',
        email: 'facturacion@novadigital.es',
        phone: '+34 910 112 233',
        hourlyRate: 30,
        currency: 'EUR',
        billingFrequency: 'monthly',
        billingStartDate: '2026-08-01',
        notes: 'Proyectos de desarrollo web mensual.',
        active: true,
        createdAt: '2026-08-01',
    },
    {
        id: 'cli_studio',
        name: 'Studio Creativo UI',
        company: 'Studio Creativo',
        email: 'hola@studiocreativo.com',
        phone: '+34 655 443 322',
        hourlyRate: 20,
        currency: 'EUR',
        billingFrequency: 'custom',
        customBillingDays: 15,
        billingStartDate: '2026-08-01',
        notes: 'Cobro quincenal (cada 15 días).',
        active: true,
        createdAt: '2026-08-01',
    },
];

export const INITIAL_WORK_ENTRIES: WorkEntry[] = [
    // Carlos (Diario)
    {
        id: 'work_1',
        clientId: 'cli_carlos',
        date: '2026-08-18',
        startTime: '09:00',
        endTime: '14:30',
        breakMinutes: 30,
        hours: 5,
        hourlyRate: 20,
        amount: 100,
        description: 'Mantenimiento del servidor e instalación de updates',
        createdAt: '2026-08-18T14:30:00Z',
    },
    {
        id: 'work_2',
        clientId: 'cli_carlos',
        date: '2026-08-19',
        startTime: '10:00',
        endTime: '14:00',
        breakMinutes: 0,
        hours: 4,
        hourlyRate: 20,
        amount: 80,
        description: 'Corrección de errores en la API de pagos',
        createdAt: '2026-08-19T14:00:00Z',
    },

    // Marta (Semanal)
    {
        id: 'work_3',
        clientId: 'cli_marta',
        date: '2026-08-17',
        startTime: '09:00',
        endTime: '14:30',
        breakMinutes: 30,
        hours: 5,
        hourlyRate: 25,
        amount: 125,
        description: 'Desarrollo de nuevos componentes de UI',
        createdAt: '2026-08-17T14:30:00Z',
    },
    {
        id: 'work_4',
        clientId: 'cli_marta',
        date: '2026-08-18',
        startTime: '09:00',
        endTime: '15:30',
        breakMinutes: 30,
        hours: 6,
        hourlyRate: 25,
        amount: 150,
        description: 'Integración del sistema de autenticación',
        createdAt: '2026-08-18T15:30:00Z',
    },
    {
        id: 'work_5',
        clientId: 'cli_marta',
        date: '2026-08-19',
        startTime: '09:00',
        endTime: '13:00',
        breakMinutes: 0,
        hours: 4,
        hourlyRate: 25,
        amount: 100,
        description: 'Revisión de código y despliegue a Staging',
        createdAt: '2026-08-19T13:00:00Z',
    },

    // Agencia Nova (Mensual)
    {
        id: 'work_6',
        clientId: 'cli_nova',
        date: '2026-08-10',
        startTime: '',
        endTime: '',
        breakMinutes: 0,
        hours: 8,
        hourlyRate: 30,
        amount: 240,
        description: 'Auditoría de rendimiento de la base de datos',
        createdAt: '2026-08-10T18:00:00Z',
    },
    {
        id: 'work_7',
        clientId: 'cli_nova',
        date: '2026-08-12',
        startTime: '09:00',
        endTime: '14:00',
        breakMinutes: 0,
        hours: 5,
        hourlyRate: 30,
        amount: 150,
        description: 'Optimización de consultas SQL y cachés Redis',
        createdAt: '2026-08-12T14:00:00Z',
    },
    {
        id: 'work_8',
        clientId: 'cli_nova',
        date: '2026-08-14',
        startTime: '10:00',
        endTime: '16:30',
        breakMinutes: 30,
        hours: 6,
        hourlyRate: 30,
        amount: 180,
        description: 'Implementación de reportes automatizados',
        createdAt: '2026-08-14T16:30:00Z',
    },

    // Studio Creativo (Quincenal 01/08 a 15/08 - ya vencido)
    {
        id: 'work_9',
        clientId: 'cli_studio',
        date: '2026-08-05',
        startTime: '09:00',
        endTime: '14:00',
        breakMinutes: 0,
        hours: 5,
        hourlyRate: 20,
        amount: 100,
        description: 'Diseño de prototipo interactivo en Figma',
        createdAt: '2026-08-05T14:00:00Z',
    },
    {
        id: 'work_10',
        clientId: 'cli_studio',
        date: '2026-08-10',
        startTime: '15:00',
        endTime: '20:00',
        breakMinutes: 0,
        hours: 5,
        hourlyRate: 20,
        amount: 100,
        description: 'Revisión con el cliente y ajuste de pantallas',
        createdAt: '2026-08-10T20:00:00Z',
    },
];

export const INITIAL_PAYMENTS: Payment[] = [
    {
        id: 'pay_1',
        clientId: 'cli_studio',
        amount: 100,
        paymentDate: '2026-08-16',
        paymentMethod: 'bizum',
        notes: 'Pago parcial del periodo quincenal (100 € de 200 €)',
        createdAt: '2026-08-16T10:00:00Z',
    },
];

export const INITIAL_PAYMENT_ITEMS: PaymentItem[] = [
    {
        id: 'pi_1',
        paymentId: 'pay_1',
        billingPeriodId: 'bp_cli_studio_2026-08-01_2026-08-15',
        amount: 100,
    },
];
